name: Tests and checks

on: push

permissions:
  contents: read

jobs:
  check:
    name: Test python${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        include:
          - python: "3.9"
            tox-env: "py39"
          - python: "3.10"
            tox-env: "py310"
          - python: "3.11"
            tox-env: "py311"
          - python: "3.12"
            tox-env: "py312"
          - python: "3.13"
            tox-env: "py313"
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.tox-env }}
      - name: Run linters
        run: tox -e pre-commit
      - name: Run type checking
        run: tox -e mypy
